# Generated by Django 3.0.8 on 2020-07-07 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hrm_branch',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('branchname', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'hrm_branch',
            },
        ),
        migrations.CreateModel(
            name='hrm_organization',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('orgname', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'hrm_organization',
            },
        ),
        migrations.CreateModel(
            name='hrm_dynamic_form_master',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=1000)),
                ('formurl', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('branch_id', models.ForeignKey(db_column='branch_id', on_delete=django.db.models.deletion.CASCADE, to='wegrenapp.hrm_branch')),
                ('organization_id', models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, to='wegrenapp.hrm_organization')),
            ],
            options={
                'db_table': 'hrm_dynamic_form_master',
            },
        ),
        migrations.CreateModel(
            name='hrm_dynamic_form_field',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('field_description', models.CharField(max_length=500)),
                ('field_type', models.IntegerField()),
                ('field_original_name', models.CharField(max_length=50)),
                ('field_hidden', models.SmallIntegerField()),
                ('field_order', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('form_master_id', models.ForeignKey(db_column='form_master_id', on_delete=django.db.models.deletion.CASCADE, to='wegrenapp.hrm_dynamic_form_master')),
            ],
            options={
                'db_table': 'hrm_dynamic_form_field',
            },
        ),
        migrations.CreateModel(
            name='hrm_dynamic_form_dropdown',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('dropdown_label', models.CharField(max_length=500)),
                ('dropdown_value', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('form_field_id', models.ForeignKey(db_column='form_field_id', on_delete=django.db.models.deletion.CASCADE, to='wegrenapp.hrm_dynamic_form_field')),
            ],
            options={
                'db_table': 'hrm_dynamic_form_dropdown',
            },
        ),
    ]
