# Generated by Django 3.0.8 on 2020-07-08 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wegrenapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HrmBranch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branchname', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'hrm_branch',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HrmDynamicFormDropdown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dropdown_label', models.CharField(max_length=255)),
                ('dropdown_value', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'hrm_dynamic_form_dropdown',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HrmDynamicFormField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_title', models.CharField(max_length=255)),
                ('field_description', models.CharField(max_length=500)),
                ('field_type', models.IntegerField()),
                ('field_original_name', models.CharField(blank=True, max_length=50, null=True)),
                ('field_hidden', models.SmallIntegerField()),
                ('field_order', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'hrm_dynamic_form_field',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HrmDynamicFormMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('form_url', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'hrm_dynamic_form_master',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HrmOrganization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orgname', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'hrm_organization',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='hrm_dynamic_form_dropdown',
            name='form_field_id',
        ),
        migrations.RemoveField(
            model_name='hrm_dynamic_form_field',
            name='form_master_id',
        ),
        migrations.RemoveField(
            model_name='hrm_dynamic_form_master',
            name='branch_id',
        ),
        migrations.RemoveField(
            model_name='hrm_dynamic_form_master',
            name='organization_id',
        ),
        migrations.DeleteModel(
            name='hrm_branch',
        ),
        migrations.DeleteModel(
            name='hrm_dynamic_form_dropdown',
        ),
        migrations.DeleteModel(
            name='hrm_dynamic_form_field',
        ),
        migrations.DeleteModel(
            name='hrm_dynamic_form_master',
        ),
        migrations.DeleteModel(
            name='hrm_organization',
        ),
    ]
